DROP TABLE if EXISTS user;
DROP TABLE if EXISTS messages;

CREATE TABLE user(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_by TEXT NOT NULL,
    message TEXT NOT NULL,
    FOREIGN KEY (sent_by) REFERENCES user (username)
);

